### ISSUE TITLE
[SPA-HotBox] Clears Free Text area

### ISSUE THREAD

**Issue by KSanders7070** [CaptainTux/VATSIM_EDST_frontend#21]
When there is free text area in an entry and then you center click the hotbox to put in the SPA, it clears the text and it shouldn't.

**Comment by KSanders7070** [comment]
It seems to clear anytime there is a change in posting areas... from DEP list to ACL it clears.

**Comment by CaptainTux** [comment]
fixed in [commit](https://github.com/CaptainTux/VATSIM_EDST_frontend/commit/c161d93a1bafe503ba9f764fbb80783a31e6ad3b)
there is an edge case remaining which is not covered by this commit:
**when an entry is automatically promoted from the DCL to ACL, the free text will be removed if one has not clicked the hotbox after entering text.**
Clicking the hotbox at any time will save the written text
